workflows: prune benchmarks to last 250 runs
To avoid this:

```
📷 Committing and pushing new benchmark data...
[benchmarks 745914423] add benchmark run for 21fe862a523bb4876346089a444444c0df063062
 1 file changed, 1 insertion(+)
exit status 1: Cloning into '.'...
Switched to a new branch 'benchmarks'
remote: warning: See https://gh.io/lfs for more information.
remote: warning: File benchmarks.json is 50.29 MB; this is larger than GitHub's recommended maximum file size of 50.00 MB
remote: warning: File 1dfc1e1acb2b9d73407434eb50b8fbae48d8e1d6 is 50.14 MB; this is larger than GitHub's recommended maximum file size of 50.00 MB
remote: warning: GH001: Large files detected. You may want to try Git Large File Storage - https://git-lfs.github.com.
To https://github.com/open-policy-agent/opa.git
 ! [remote rejected]     benchmarks -> benchmarks (cannot lock ref 'refs/heads/benchmarks': is at 7a136a304de139fdddcfea6784eb367a7ff78154 but expected 3fd93c504ede8a7bef8035ba2c4609efd1fa1d68)
error: failed to push some refs to 'https://github.com/open-policy-agent/opa.git'
```

Signed-off-by: Stephan Renatus <stephan.renatus@gmail.com>