partial eval and not bug: MWE
I'm afraid I couldn't make this much simpler without the error going away ;)

The error is that during PartialEval of this combiniation of policy and data,
we end up getting:

    rego_type_error: conflicting rules named __not4_2__ found

Looking at this, the generated rules for the line

    not wildcard(pol_sub)

are
    __not4_2__ = true { true }
    __not4_2__(pol_sub) = true { data.authz.wildcard(pol_sub) }

I've tried chasing that bug, I wasn't successful. Only fund that at some point,
`pol_sub` makes it into e.saveSet. While I'm suspecting that it shouldn't go
there (it's not "unknown" after all), I also haven't understood the logic of
what's happening, and thus hit a wall there.

Signed-off-by: Stephan Renatus <srenatus@chef.io>